### ISSUE TITLE
geom_line(), geom_point(), Multiple Lines

### ISSUE THREAD

**Issue by jpryda** [yhat/ggplot#489] opened 2016-06-08 14:17 UTC
![gg_hourly_comparison_social_partnership_segment](https://cloud.githubusercontent.com/assets/7294160/15897291/f364af9a-2d61-11e6-9ca9-b22a7ea1468a.png)

geom_line() and geom_point() fail to output multiple lines correctly.  It seems geom_point() picks up the second variable in the melted df and geom_line() the first.  geom_step() works fine however.  Running geom_line() alone (without geom_point) only outputs a single red line.

```
gg_hourly_plot = ggplot(melted_df, aes(x='hour', y='value', color='day')) +\
                                geom_line(size=2.25, alpha=0.7) +\
                                geom_point(size=25) +\
                                ggtitle(self.full_name + ": Yesterday's Performance") +\
                                scale_y_continuous(name='Unique Visitors', labels='comma') +\
                                ylim(low=0) +\
                                scale_x_continuous(name="Hour", breaks=range(0,24,2), limits=(-1,24))

hourly_fname = "./daily_images/gg_hourly_comparison_" + self.short_name
gg_hourly_plot.save(filename=hourly_fname + ".png", width=20.5, height=5)
```

**Comment by glamp** [comment] 2016-06-08 15:16
Hey thanks for submitting an issue. Can you provide a reproducible example?

**Comment by sebastian-nagel** [comment] 2016-06-13 22:20
Facing the same problem (tested with 0.9.3, 0.9.4 and current version from github):
```
from ggplot import *
import pandas

df = pandas.DataFrame({'a': range(0,3), 'b': range(1,4)})
df['x'] = df.index
df = pandas.melt(df, id_vars='x')

print ggplot(aes(x='x', y='value', color='variable'), df) + geom_line() + geom_point()
```

**Comment by Minzc** [comment] 2016-06-22 08:20
Having the same problem. 

import pandas as pd
meat_lng = pd.melt(meat, id_vars=['date'])
ggplot(meat_lng, aes(x='date', y='value', color='variable')) + geom_line()

This the example provided in your tutorial.

**Comment by glamp** [comment] 2016-06-29 21:10
Seems to be a sort issue. The second set of data is coming back as NaNs

```
[(nan, nan), (nan, nan), (nan, nan)]
```
Should be an easy fix.

**Comment by glamp** [comment] 2016-06-29 21:17
will be in next release

e17ec4464fc33716ae08a4fb703bf3b0f96b3398

**Closed by glamp** 2016-06-29 21:17 UTC
